Q.1
WRITE A PROGRAM TO CREATE A NUMPY 1D ARRAY WITH 5 ELEMENTS AND PERFORM BASIC OPERATIONS LIKE :
1)..ADDITION OF 2 IN ALL ELEMENTS
2)..MULTIPLY 3 WITH ALL THE ELEMENTS
3)..DIVIDE EVERY ELEMENT BY 2

In [1]:
import numpy as np
elements=np.array([10,20,30,40,50])
add_result=elements+2
print("addition:",add_result)
multiply=elements*3
print("multplication:",multiply)
divide=elements/2
print("division:",divide)

addition: [12 22 32 42 52]
multplication: [ 30  60  90 120 150]
division: [ 5. 10. 15. 20. 25.]


Q.2
A)REVERSE THE NUMPY ARRAY:ARR=NP.ARRAY([1,2,3,6,4,5])

In [23]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
reversed_arr=arr[::-1]
print("reversed array :",reversed_arr)

reversed array : [5 4 6 3 2 1]


B)FIND THE MOST FREQUENT VALUE AND THEIR INDICES(S) IN THE FOLLOWING ARRAYS:
I. X=NP.ARRAY([1,2,3,4,5,1,2,1,1,1])
II.Y=NP.ARRAY([1,1,1,2,3,4,2,4,3,3])

In [27]:
import numpy as np
from collections import Counter
def most_frequent(arr):
    count=Counter(arr)
    most_common=count.most_common(1)[0]
    indices=np.where(arr==most_common[0])
    return most_common ,indices
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
xvalue,xindices=most_frequent(x)
yvalue,yindices=most_frequent(y)
print(f"most frequent value in x:{xvalue},indices:{xindices}")
print(f"most frequent value in y:{yvalue},indices:{yindices}")

most frequent value in x:(1, 5),indices:(array([0, 5, 7, 8, 9], dtype=int64),)
most frequent value in y:(1, 3),indices:(array([0, 1, 2], dtype=int64),)


Q.3
FOR THE GIVEN 2-D ARRAY ARR=NP.ARRAY([10,20,30],[40,50,60],[70,80,90]),ACCESS ELEMENTS USING ROW AND COLUMN INDICES AS FOLLOWS:
A) ACCESS 1ST ROW,2ND COLUMN
B) ACCESS 3RD ROW ,1ST COLUMN

In [33]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
element1=arr[0,1]
print("the element of first row and secind column is:",element1)
element2=arr[2,0]
print("the element f third row and first column is :",element2)

the element of first row and secind column is: 20
the element f third row and first column is : 70


Q.4
WRITE PROGRAM TO CREATE AN 1-D NUMPY ARRAY NAMED <<YOUR NAME>> WITH EVENLY SPACED 25 NUMBERS FROM 10 TO 100 USING LINSPACE().PRINT THE DIMENSIONS OF THE ARRAY, SHAPE,TOTAL ELEMENTS,THE DATA TYPE OF EACH ELEMENT AND TOTAL NUMBER OF BYTES CONSUMED BY THE ARRAY.FIND THE TRANSPOSE OF THIS ARRAY USING RESHAPE() ATTTRIBUTE.CAN WE DO THE SAME WUTH .T ATTRIBUTE?

In [37]:
import numpy as np
Your_Name = np.linspace(10, 100, 25)  
print("Array:", Your_Name)
print("Dimensions:", Your_Name.ndim) 
print("Shape:", Your_Name.shape) 
print("Total Elements:", Your_Name.size)  
print("Data Type:", Your_Name.dtype) 
print("Total Bytes Consumed:", Your_Name.nbytes)  
transpose_array = Your_Name.reshape(25, 1)  
print("\nTranspose using reshape():\n", transpose_array)
transpose_T = Your_Name.T  
print("\nTranspose using T attribute:\n", transpose_T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q.5
CREATE A 2-D ARRAY OF THREE ROWS AND FOUR COLUMN ,NAMED UCS420_<YOURNAME>> WITH THE FOLLOWING VALUES-10,20,30,40,50,60,70,80,90,15,20,35.
COMPUTE THE MEAN ,MEDIAN, MAX,MIN,UNIQUE ELEMENTS.RESHAPE THE ARRAY TO FOUR ROWS AND THREE COLUMNS AND NAME IT AS RESHAPED _UCS420<YOUR_NAME>>.
RESIZE THE ARRAY TO TWO ROWS AND THREE COLUMNS AND NAMED IT AS RESIZED_UCS420<YOUR_NAME>>.

In [47]:
import numpy as np
ucs420_yourname=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean_value=np.mean(ucs420_yourname)
median_value=np.median(ucs420_yourname)
max_value=np.max(ucs420_yourname)
min_value=np.min(ucs420_yourname)
unique_elements=np.unique(ucs420_yourname)
print("mean:",mean_value)
print("medain:",median_value)
print("max:",max_value)
print("min:",min_value)
print("unique elements:",unique_elements)
reshaped_ucs420_yourname=ucs420_yourname.reshape(4,3)
print("\n reshaped array :\n",reshaped_ucs420_yourname)
resized_ucs420_yourname=np.resize(ucs420_yourname,(2,3))
print("\nresized array (2*3):\n",resized_ucs420_yourname)


mean: 43.333333333333336
medain: 37.5
max: 90
min: 10
unique elements: [10 15 20 30 35 40 50 60 70 80 90]

 reshaped array :
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

resized array (2*3):
 [[10 20 30]
 [40 50 60]]
